---
title: "BatchPlot"
author: "Marc"
date: "5/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Libraries
```{r include=FALSE}
set.seed(1234)
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
library(readxl)
library(ggpubr)

theme_set(theme_minimal())

plot_pca <- function(tmp1, tmp2, color_label, ranks = 10){
  
  tmp3 <- prcomp(tmp2, center = T, scale. = T, rank. = ranks)

  pdata <- 
    tmp3$x %>% 
    as_tibble() %>% 
    bind_cols(tmp1 %>% select(all_of(color_label)) %>% mutate_all(as.factor)) %>% 
    pivot_longer(cols = seq(1, ncol(.)-length(color_label), by=2)) %>% 
    select(x_val = value, x_name = name, everything()) %>% 
    pivot_longer(cols = starts_with("PC")) %>% 
    select(x_name, y_name = name,x_val, y_val = value, everything()) %>%
    mutate(name = paste(x_name, "vs", y_name),
           name = factor(name, levels = sort(name) %>% unique())) %>% 
    filter(as.numeric(gsub("PC", "", x_name)) + 1 == as.numeric(gsub("PC", "", y_name)))
  
  pca_plot <- pdata %>% 
    ggplot(aes(x=x_val, y=y_val))+
    geom_point(aes_string(fill = color_label), shape = 21, color = "white")+
    facet_grid(~name, scales = "free")+
    labs(x = "", y = "")+
    NULL
  return(pca_plot)
}

```
# Loading files
```{r}
WD <- getwd()
if(WD!="C:/Users/mysit/Documents/Bioinformatica/Semestre_4/workflowr/data"){
  setwd("../workflowr/data")
}

sampleorder <- read_excel("../data/sample_order_traceage_wp2_sample_overview.xlsx") %>% as.data.frame()
sampleorder<-sampleorder %>% select(Sample, `Injection order positive`) 
names(sampleorder)[1]<-"sample"

mdf_orig <- read_rds(file="mdf_original.rds")
original <- merge(mdf_orig,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_proc <- read_rds(file = "mdf_processed.rds")
proc <- merge(mdf_proc,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_sumtoone <- read_rds(file = "mdf_sumtoone.rds")
sumtoone <- merge(mdf_sumtoone,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_robustnorm<- read_rds(file = "mdf_robustnorm.rds")
robustnorm <- merge(mdf_robustnorm,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_meansnorm<- read_rds(file = "mdf_meansnorm.rds")
meansnorm <- merge(mdf_meansnorm,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_wave2good<- read_rds(file = "mdf_wave2good.rds")
wave2good <- merge(mdf_wave2good,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_combat<- read_rds(file = "mdf_combat.rds")
combat <- merge(mdf_combat,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_Rcpm<- read_rds(file = "mdf_Rcpm.rds")
Rcpm <- merge(mdf_Rcpm,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_MSBox<- read_rds(file = "mdf_MSBox.rds")
MSBox <- merge(mdf_MSBox,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)
```

# Making plots
```{r fig.asp = 0.5, fig.width = 10}
#Finding a metabolite with high variance
variances <- apply(X=proc[7:(ncol(proc))], MARGIN=2, FUN=var)
sorted <- sort(variances, decreasing=TRUE, index.return=TRUE)$ix[10:20] # replace 2 with 100 ...
names(original[, sorted])


#proc %>% ggplot(aes(`Injection order positive`,M730T875)) + geom_point(aes(colour = factor(batch)))

porig <- original %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired") +labs(color = "Batch")

pproc <- proc %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

psumtoone <- sumtoone %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

probustnorm <- robustnorm %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

pmeansnorm <- meansnorm %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

pwave2good <- wave2good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

pcombat <- combat %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

pRcpm <- Rcpm %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

pMSBox <- MSBox %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")



ggarrange(porig, pproc, psumtoone, probustnorm,pmeansnorm,pwave2good,pcombat,pRcpm,pMSBox,
                    labels = c("Original", "Processed", "SumToOne", "probustnorm","pmeansnorm","pwave2good","ComBat","pRcpm","pMSBox"),font.label = list(size = 8, color = "black"),
                    ncol = 3, nrow = 3,common.legend = TRUE, legend = "bottom")
```

# Comparing different WaveICA2.0 parameters
```{r}
mdf_wave2good<- read_rds(file = "mdf_wave2good.rds")
wave2good <- merge(mdf_wave2good,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_wave07good.rds<- read_rds(file = "mdf_wave07good.rds")
wave07good <- merge(mdf_wave07good.rds,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_wave05good<- read_rds(file = "mdf_wave05good.rds")
wave05good <- merge(mdf_wave05good,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_wave03good<- read_rds(file = "mdf_wave03good.rds")
wave03good <- merge(mdf_wave03good,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

mdf_wave0good<- read_rds(file = "mdf_wave0good.rds")
wave0good <- merge(mdf_wave0good,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)
```

```{r}
pwave2good <- wave2good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired") +labs(color = "Batch")
pwave07good <- wave07good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")
pwave05good <- wave05good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")
pwave03good <- wave03good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")
pwave0good <- wave0good %>% ggplot(aes(`Injection order positive`,M662T825)) + geom_point(aes(colour = factor(batch))) + scale_color_brewer(palette = "Paired")

ggarrange(pwave2good, pwave07good, pwave05good, pwave03good, pwave0good,
                    labels = c("0.9", "0.7", "0.5", "0.3","0"),font.label = list(size = 10, color = "black"),
                    ncol = 3, nrow = 2,common.legend = TRUE, legend = "bottom")
```

