---
title: "BN tests"
author: "Marc"
date: "12/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Libraries
```{r include=FALSE}
set.seed(1234)
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
theme_set(theme_minimal())
```
```{r}
plot_pca <- function(tmp1, tmp2, color_label, ranks = 10){
  
  tmp3 <- prcomp(tmp2, center = T, scale. = T, rank. = ranks)

  pdata <- 
    tmp3$x %>% 
    as_tibble() %>% 
    bind_cols(tmp1 %>% select(all_of(color_label)) %>% mutate_all(as.factor)) %>% 
    pivot_longer(cols = seq(1, ncol(.)-length(color_label), by=2)) %>% 
    select(x_val = value, x_name = name, everything()) %>% 
    pivot_longer(cols = starts_with("PC")) %>% 
    select(x_name, y_name = name,x_val, y_val = value, everything()) %>%
    mutate(name = paste(x_name, "vs", y_name),
           name = factor(name, levels = sort(name) %>% unique())) %>% 
    filter(as.numeric(gsub("PC", "", x_name)) + 1 == as.numeric(gsub("PC", "", y_name)))
  
  pca_plot <- pdata %>% 
    ggplot(aes(x=x_val, y=y_val))+
    geom_point(aes_string(fill = color_label), shape = 21, color = "white")+
    facet_grid(~name, scales = "free")+
    labs(x = "", y = "")+
    NULL
  return(pca_plot)
}

```


# Data loading
```{r}
set.seed(1234)
WD <- getwd()
if(WD!="C:/Users/mysit/Documents/Bioinformatica/Semestre_4/workflowr/data"){
  setwd("../workflowr/data")
}

mdf <- read_rds(file = "mdf_processed.rds")
#mdf<-mdf %>% gather(key="mz",value="values",6:ncol(mdf)) %>% spread(mz,values)

results <- data.frame(TrainRMSE = as.numeric(),TrainRsquared = as.numeric(),TrainMAE = as.numeric(),method = as.character(),Name = as.character(),QC = as.character())
```

# Simple BN subsctracting the mean of each batch

## Removing the means of each batch using the colMeans() function

https://www.gastonsanchez.com/visually-enforced/how-to/2014/01/15/Center-data-in-R/
```{r}
#Making a function to center the means
center_colmeans <- function(x) {
    xcenter = colMeans(x)
    x - rep(xcenter, rep.int(nrow(x), ncol(x)))
}


batch1<-mdf %>% 
  filter(batch==1)
mean_removed<-(center_colmeans(batch1[6:ncol(batch1)]))
batch1[ , colnames(batch1) %in% colnames(mean_removed)] <- mean_removed

batch2<-mdf %>% 
  filter(batch==2)
mean_removed<-(center_colmeans(batch2[6:ncol(batch2)]))
batch2[ , colnames(batch2) %in% colnames(mean_removed)] <- mean_removed

batch3<-mdf %>% 
  filter(batch==3)
mean_removed<-(center_colmeans(batch3[6:ncol(batch3)]))
batch3[ , colnames(batch3) %in% colnames(mean_removed)] <- mean_removed

batch2b<-mdf %>% 
  filter(batch=="2b")
mean_removed<-(center_colmeans(batch2b[6:ncol(batch2b)]))
batch2b[ , colnames(batch2b) %in% colnames(mean_removed)] <- mean_removed

batchb2<-mdf %>% 
  filter(batch=="b2")
mean_removed<-(center_colmeans(batchb2[6:ncol(batchb2)]))
batchb2[ , colnames(batchb2) %in% colnames(mean_removed)] <- mean_removed

batchb3<-mdf %>% 
  filter(batch=="b3")
mean_removed<-(center_colmeans(batchb3[6:ncol(batchb3)]))
batchb3[ , colnames(batchb3) %in% colnames(mean_removed)] <- mean_removed

batchb<-mdf %>% 
  filter(batch=="b")
mean_removed<-(center_colmeans(batchb[6:ncol(batchb)]))
batchb[ , colnames(batchb) %in% colnames(mean_removed)] <- mean_removed

batchna<-mdf %>% 
  filter(is.na(batch))
mean_removed<-(center_colmeans(batchna[6:ncol(batchna)]))
batchna[ , colnames(batchna) %in% colnames(mean_removed)] <- mean_removed

test<-rbind(batch1,batch2,batch3,batch2b,batchb2,batchb3,batchb,batchna)

rm(batch1,batch2,batch3,batch2b,batchb2,batchb3,batchb,batchna)
mdf<-test[order(test$sample_id),]  
mdf[is.na(mdf)] <- 0
```

## PCA
```{r}
rm(rowinfo,raw)
raw     <-  mdf[6:(ncol(mdf))]
rowinfo <- mdf[0:5]
rowinfo <- tibble::rowid_to_column(rowinfo, "rowid")

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
plot_pca(tmp1,tmp2,color_label = "age")
```

## Model
```{r}
training_DF <- mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

fit1 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[1,] = data.frame(getTrainPerf(fit1), Name = paste0("fit1"), QC = "4th_root + PCA outlier removal + Bad features removal + QC and Bind samples + Mean BN")

results
```



# Saving the model
```{r}
saveRDS(fit1, "bn_means.rds")
```

