---
title: "Combat"
author: "Marc"
date: "18/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Libraries

```{r include=FALSE}
set.seed(1234)
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
library(readxl)
theme_set(theme_minimal())
```
```{r}
plot_pca <- function(tmp1, tmp2, color_label, ranks = 10){
  
  tmp3 <- prcomp(tmp2, center = T, scale. = T, rank. = ranks)

  pdata <- 
    tmp3$x %>% 
    as_tibble() %>% 
    bind_cols(tmp1 %>% select(all_of(color_label)) %>% mutate_all(as.factor)) %>% 
    pivot_longer(cols = seq(1, ncol(.)-length(color_label), by=2)) %>% 
    select(x_val = value, x_name = name, everything()) %>% 
    pivot_longer(cols = starts_with("PC")) %>% 
    select(x_name, y_name = name,x_val, y_val = value, everything()) %>%
    mutate(name = paste(x_name, "vs", y_name),
           name = factor(name, levels = sort(name) %>% unique())) %>% 
    filter(as.numeric(gsub("PC", "", x_name)) + 1 == as.numeric(gsub("PC", "", y_name)))
  
  pca_plot <- pdata %>% 
    ggplot(aes(x=x_val, y=y_val))+
    geom_point(aes_string(fill = color_label), shape = 21, color = "white")+
    facet_grid(~name, scales = "free")+
    labs(x = "", y = "")+
    NULL
  return(pca_plot)
}

```

# Data and models loading

```{r}
set.seed(1234)
WD <- getwd()
if(WD!="C:/Users/mysit/Documents/Bioinformatica/Semestre_4/workflowr/data"){
  setwd("../workflowr/data")
}
mdf <- read_rds(file = "mdf_processed.rds")
mdf<-data.frame(mdf)



sampleorder <- read_excel("../data/sample_order_traceage_wp2_sample_overview.xlsx") %>% as.data.frame()

sampleorder<-sampleorder %>% select(Sample, `Injection order positive`) 

names(sampleorder)[1]<-"sample"


results <- data.frame(TrainRMSE = as.numeric(),TrainRsquared = as.numeric(),TrainMAE = as.numeric(),method = as.character(),Name = as.character(),QC = as.character())

#Some samples have different ID than on the original dataframe. 
merged <- merge(mdf,sampleorder,by=c("sample"), all = T) 
#Removing them and keeping the ones I know are correct leaves me with less rows
merged <- merge(mdf,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

```

# Loading ComBat
https://rdrr.io/bioc/sva/man/ComBat.html

```{r}
library(sva)
```

```{r}
mdf[is.na(mdf)] <- 0

#mdf<-mdf[order(mdf$batch),]  
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)

rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)


batches<-(mdf$batch)
test<-mdf %>% select(starts_with("M"))
test<-as.matrix(test)
#Group may be age
#group<-as.numeric(mdf$age)
```

```{r}
combat <- ComBat(dat=t(test), batch=batches, par.prior=TRUE, prior.plots=FALSE)
combat <- t(combat)
combat <- cbind(rowinfo,combat)
```

## Model
```{r}
training_DF <- combat %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 5, verboseIter = F, savePredictions = "final")

fit1 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[1,] = data.frame(getTrainPerf(fit1), Name = paste0("fit1"), QC = "4th_root + PCA outlier removal + Bad features removal + Combat")

results

combat_model<-fit1
```



# Saving the model
```{r}
saveRDS(combat_model, "combat_model.rds")
```

