---
title: "regression_thesis"
date: ""
output: 
  html_document:
    theme: united
    code_folding: hide
    toc: true
    toc_depth: 2 
editor_options: 
  chunk_output_type: console
---

# Libraries
```{r include=FALSE}
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
```

# Data loading
```{r}
#setwd("../workflowr/data")
mdf <- read_csv("TraceAge_bloodspots_t3_pos_clean.csv")

mdf<-mdf %>% gather(key="mz",value="values",6:ncol(mdf)) %>% spread(mz,values)
```

# PCA 2d
```{r}
pca_df<-mdf %>% filter(type=="sample")
```
```{r}
pr.out <- prcomp(pca_df[,6:(ncol(mdf))], scale. = TRUE)

autoplot(pr.out, data = pca_df, colour = 'age', shape="batch", size=2)
```

# PC1,2,3
```{r}
dat_3d <- pr.out$x[,1:3] %>% as_tibble() %>% mutate(group = pca_df$batch, pen=pca_df$age)

fig <- plot_ly(dat_3d, x = ~PC1, y = ~PC2, z = ~PC3, 
               color = ~group,colors = c("black", "darkorange", "dodgerblue","darkred"), size = I(100))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'PC1'),
                                   yaxis = list(title = 'PC2'),
                                   zaxis = list(title = 'PC3')))
fig
```

# PC4,5,6
```{r}
dat_3d <- pr.out$x[,4:6] %>% as_tibble() %>% mutate(group = pca_df$batch, pen=pca_df$age)

fig <- plot_ly(dat_3d, x = ~PC4, y = ~PC5, z = ~PC6, 
               color = ~group,colors = c("black", "darkorange", "dodgerblue","darkred"), size = I(100))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'PC4'),
                                   yaxis = list(title = 'PC5'),
                                   zaxis = list(title = 'PC6')))
fig
```


# Impute (zero) and Fourth root transformation
## Changing the format of the table
```{r}
test_df<-mdf %>% gather(key="mz",value="values",6:ncol(mdf))
```
## Imputing zero
```{r}
test_df$values[is.na(test_df$values)] <- 0
```
## Fourth root transformation
```{r}
test_df$values <- test_df$values^0.25
```
## Changing back to the original table
```{r}
mdf <- test_df %>% spread(mz,values)
```

# PCA 2d
```{r}
pca_df<-mdf %>% filter(type=="sample")
```
```{r}
pr.out <- prcomp(pca_df[,6:(ncol(mdf))], scale. = TRUE)

autoplot(pr.out, data = pca_df, colour = 'age', shape="batch", size=2)
```

# PC1,2,3
```{r}
dat_3d <- pr.out$x[,1:3] %>% as_tibble() %>% mutate(group = pca_df$batch, pen=pca_df$age)

fig <- plot_ly(dat_3d, x = ~PC1, y = ~PC2, z = ~PC3, 
               color = ~group,colors = c("black", "darkorange", "dodgerblue","darkred"), size = I(100))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'PC1'),
                                   yaxis = list(title = 'PC2'),
                                   zaxis = list(title = 'PC3')))
fig
```

# PC4,5,6
```{r}
dat_3d <- pr.out$x[,4:6] %>% as_tibble() %>% mutate(group = pca_df$batch, pen=pca_df$age)

fig <- plot_ly(dat_3d, x = ~PC4, y = ~PC5, z = ~PC6, 
               color = ~group,colors = c("black", "darkorange", "dodgerblue","darkred"), size = I(100))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'PC4'),
                                   yaxis = list(title = 'PC5'),
                                   zaxis = list(title = 'PC6')))
fig
```

# The next steps on the original rmd are the batch normalization? Aka removing PCA outliers and such?? 

# Make a Training/Test from the data and try regression on age 
```{r}
training_DF <- mdf %>% select(-sample,-batch,-type,-sample_id)
training_DF[is.na(training_DF)] <- 0
training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age
```

```{r}
trControl <- trainControl(method = "repeatedcv", number = 5, verboseIter = T)

fit <- train(x = training_x, 
             y = training_y, 
        method = "lm",
        tuneLength = 2,
     trControl = trControl
    )

fit
predictions<-extractPrediction(list(my_rf = fit), testX = training_x, testY = training_y)
```

```{r}
ggplot(data = predictions, aes(x=obs, y=pred)) + geom_point() + geom_abline()
```

