---
title: "Visualizations and comparisons"
author: "Marc"
date: "18/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Libraries

```{r include=FALSE}
set.seed(1234)
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
theme_set(theme_minimal())
```

```{r}
plot_pca <- function(tmp1, tmp2, color_label, ranks = 10){
  
  tmp3 <- prcomp(tmp2, center = T, scale. = T, rank. = ranks)

  pdata <- 
    tmp3$x %>% 
    as_tibble() %>% 
    bind_cols(tmp1 %>% select(all_of(color_label)) %>% mutate_all(as.factor)) %>% 
    pivot_longer(cols = seq(1, ncol(.)-length(color_label), by=2)) %>% 
    select(x_val = value, x_name = name, everything()) %>% 
    pivot_longer(cols = starts_with("PC")) %>% 
    select(x_name, y_name = name,x_val, y_val = value, everything()) %>%
    mutate(name = paste(x_name, "vs", y_name),
           name = factor(name, levels = sort(name) %>% unique())) %>% 
    filter(as.numeric(gsub("PC", "", x_name)) + 1 == as.numeric(gsub("PC", "", y_name)))
  
  pca_plot <- pdata %>% 
    ggplot(aes(x=x_val, y=y_val))+
    geom_point(aes_string(fill = color_label), shape = 21, color = "white")+
    facet_grid(~name, scales = "free")+
    labs(x = "", y = "")+
    NULL
  return(pca_plot)
}

```

# Data and models loading

```{r}
WD <- getwd()
if(WD!="C:/Users/mysit/Documents/Bioinformatica/Semestre_4/workflowr/data"){
  setwd("../workflowr/data")
}
load("models.RData")
H_BN_means <- readRDS("bn_means.rds")
Combat <- readRDS("../data/combat_model.rds")
load("../data/models_waveICA2.0.RData")
```

# Comparing the two normalization methods

```{r eval=FALSE, include=FALSE}
error %>% filter(model=="fit6"|model=="fit7") %>% ggplot(aes(x=rep,y=rmse, fill=rep)) + geom_bar(stat="identity",position=position_stack()) + 
  scale_fill_brewer(palette="Set3") + geom_text(aes(label=round(rmse,4)), position = position_stack(vjust = 0.5)) + 
  facet_wrap(~model)
```

```{r}
error %>% filter(model=="fit6"|model=="fit7") %>% ggplot(aes(x=model,y=rmse, color=model)) + geom_boxplot(outlier.colour = "red") + geom_boxplot(outlier.colour="red", outlier.shape=1,
                outlier.size=8) +
  geom_jitter(shape=16, position=position_jitter(0)) +
  scale_color_brewer(palette="Dark2")
```


# Getting the errors of fit 8
```{r}
results[8,] = data.frame(getTrainPerf(H_BN_means), Name = paste0("H_BN_means"), QC = "4th_root + PCA outlier removal + Bad features removal + Mean BN")

error1<-H_BN_means$pred %>%
  filter(alpha == H_BN_means$bestTune$alpha & lambda == H_BN_means$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "H_BN_means")

error<-rbind(error,error1)
```

# Getting the errors of WAVEICA files
```{r}
results[9,] = data.frame(getTrainPerf(waveICA2.0_realorder), Name = paste0("waveICA2.0_realorder"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")

error1<-waveICA2.0_realorder$pred %>%
  filter(alpha == waveICA2.0_realorder$bestTune$alpha & lambda == waveICA2.0_realorder$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "I_waveICA2.0_realorder")

error<-rbind(error,error1)
```


# Getting the errors of ComBat

```{r}
results[11,] = data.frame(getTrainPerf(Combat), Name = paste0("Combat"), QC = "4th_root + PCA outlier removal + Bad features removal + ComBat")

error1<-Combat$pred %>%
  filter(alpha == Combat$bestTune$alpha & lambda == Combat$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "J_ComBat")

error<-rbind(error,error1)
```

# Plotting
## Everything
```{r}
error %>% ggplot(aes(x=model,y=rmse, color=model)) + geom_boxplot(outlier.colour = "red") + geom_boxplot(outlier.colour="red", outlier.shape=1,
                outlier.size=8) +  geom_jitter(shape=16, position=position_jitter(0))
```
## The Normalizations

```{r}
test<-error %>% slice(26:140)
test %>% ggplot(aes(x=model,y=rmse, color=model)) + geom_boxplot(outlier.colour = "red") + geom_boxplot(outlier.colour="red", outlier.shape=1,
                outlier.size=8) +  geom_jitter(shape=16, position=position_jitter(0)) +
  scale_color_brewer(palette="Dark2")
```
