---
title: "WaveICA2_0"
author: "Marc"
date: "18/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Libraries

```{r include=FALSE}
set.seed(1234)
library(ggplot2)
library(ggfortify)
library(plotly)
library(cowplot)
library(caret)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggrepel)
library(patchwork)
library(readxl)
library(ggpubr)
theme_set(theme_minimal())

plot_pca <- function(tmp1, tmp2, color_label, ranks = 4){
  
  tmp3 <- prcomp(tmp2, center = T, scale. = T, rank. = ranks)

  pdata <- 
    tmp3$x %>% 
    as_tibble() %>% 
    bind_cols(tmp1 %>% select(all_of(color_label)) %>% mutate_all(as.factor)) %>% 
    pivot_longer(cols = seq(1, ncol(.)-length(color_label), by=2)) %>% 
    select(x_val = value, x_name = name, everything()) %>% 
    pivot_longer(cols = starts_with("PC")) %>% 
    select(x_name, y_name = name,x_val, y_val = value, everything()) %>%
    mutate(name = paste(x_name, "vs", y_name),
           name = factor(name, levels = sort(name) %>% unique())) %>% 
    filter(as.numeric(gsub("PC", "", x_name)) + 1 == as.numeric(gsub("PC", "", y_name)))
  
  pca_plot <- pdata %>% 
    ggplot(aes(x=x_val, y=y_val))+
    geom_point(aes_string(fill = color_label), shape = 21, color = "white")+
    facet_grid(~name, scales = "free")+
    labs(x = "", y = "")+
    NULL
  return(pca_plot)
}

```

# Data and models loading

```{r}
set.seed(1234)
WD <- getwd()
if(WD!="C:/Users/mysit/Documents/Bioinformatica/Semestre_4/workflowr/data"){
  setwd("../workflowr/data")
}


mdf <- read_rds(file = "mdf_processed.rds")

sampleorder <- read_excel("../data/sample_order_traceage_wp2_sample_overview.xlsx") %>% as.data.frame()

sampleorder<-sampleorder %>% select(Sample, `Injection order positive`) 

names(sampleorder)[1]<-"sample"


results <- data.frame(TrainRMSE = as.numeric(),TrainRsquared = as.numeric(),TrainMAE = as.numeric(),method = as.character(),Name = as.character(),QC = as.character())

#Some samples have different ID than on the original dataframe. 
merged <- merge(mdf,sampleorder,by=c("sample"), all = T) 
#Removing them and keeping the ones I know are correct leaves me with less rows
merged <- merge(mdf,sampleorder,by=c("sample"), all = F) %>% relocate(`Injection order positive`, .before = sample)

```

# Loading WaveICA2.0

<https://github.com/dengkuistat/WaveICA_2.0>

<https://www.metaboanalyst.ca/docs/RTutorial.xhtml>

## Installation

```{r}
#devtools::install_github("dengkuistat/WaveICA_2.0",host="https://api.github.com")
#install.packages("remotes")
#devtools::install_github("dengkuistat/WaveICA",host="https://api.github.com", force=T)
```

```{r}
library(WaveICA2.0)
#library(WaveICA)
```

# WaveICA 2.0 on original data

```{r eval=FALSE, include=FALSE}
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)

ms = list()
test<-mdf %>% select(starts_with("M")) %>% as.matrix()
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

tmp3 <- WaveICA_2.0(test, Injection_Order = 1:nrow(test), Cutoff = 0.1, wf = "haar", K = 20, alpha = 0)
tmp3 <- tmp3$data_wave
wave_original_mdf <- tmp3 %>% as_tibble()

wave_original_mdf <- cbind(rowinfo,wave_original_mdf)

```

# WaveICA 2.0 with the provided sample order

```{r}

#Making a waaay smaller df
#merged <- merged[1:100]
merged<-merged %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)

ms = list()
test2<-merged %>% select(starts_with("M")) %>% as.matrix()
rowinfo <- merged %>% select(rowid, sample, age, batch, type, sample_id)
order <- merged$`Injection order positive`

tmp4 <- WaveICA_2.0(test2, Injection_Order = order, Cutoff = 1, wf = "haar", K = 10, alpha = 0.1)
tmp4 <- tmp4$data_wave
wave_withorder_mdf <- tmp4 %>% as_tibble()
wave_withorder_mdf <- cbind(rowinfo,wave_withorder_mdf)
write_rds(wave_withorder_mdf, file = "mdf_wave2good.rds")

tmp5 <- WaveICA_2.0(test2, Injection_Order = order, Cutoff = 0, wf = "haar", K = 10, alpha = 0.1)
tmp5 <- tmp5$data_wave
wave_0_mdf <- tmp5 %>% as_tibble()
wave_0_mdf <- cbind(rowinfo,wave_0_mdf)
write_rds(wave_0_mdf, file = "mdf_wave0good.rds")

tmp6 <- WaveICA_2.0(test2, Injection_Order = order, Cutoff = 0.3, wf = "haar", K = 10, alpha = 0.1)
tmp6 <- tmp6$data_wave
wave_0.3_mdf <- tmp6 %>% as_tibble()
wave_0.3_mdf <- cbind(rowinfo,wave_0.3_mdf)
write_rds(wave_0.3_mdf, file = "mdf_wave03good.rds")

tmp7 <- WaveICA_2.0(test2, Injection_Order = order, Cutoff = 0.5, wf = "haar", K = 10, alpha = 0.1)
tmp7 <- tmp7$data_wave
wave_0.5_mdf <- tmp7 %>% as_tibble()
wave_0.5_mdf <- cbind(rowinfo,wave_0.5_mdf)
write_rds(wave_0.5_mdf, file = "mdf_wave05good.rds")

tmp8 <- WaveICA_2.0(test2, Injection_Order = order, Cutoff = 0.7, wf = "haar", K = 10, alpha = 0.1)
tmp8 <- tmp8$data_wave
wave_0.7_mdf <- tmp8 %>% as_tibble()
wave_0.7_mdf <- cbind(rowinfo,wave_0.7_mdf)
write_rds(wave_0.7_mdf, file = "mdf_wave07good.rds")
```

# PCAs
```{r fig.asp = 0.6, fig.width = 10}
#Cutoff of 1
mdf <- wave_withorder_mdf
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

rm(rowinfo)
raw     <-  mdf[7:(ncol(mdf))]
rowinfo <- mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
Wavecut1<-plot_pca(tmp1,tmp2,color_label = "batch")

#After WaveICA2.0 Cutoff of 0.7
mdf <- wave_0.7_mdf
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

rm(rowinfo)
raw     <-  mdf[7:(ncol(mdf))]
rowinfo <- mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
Wavecut0.7<-plot_pca(tmp1,tmp2,color_label = "batch")

#After WaveICA2.0 Cutoff of 0.5
mdf <- wave_0.5_mdf
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

rm(rowinfo)
raw     <-  mdf[7:(ncol(mdf))]
rowinfo <- mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
Wavecut0.5<-plot_pca(tmp1,tmp2,color_label = "batch")

#After WaveICA2.0 Cutoff of 0.3
mdf <- wave_0.3_mdf
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

rm(rowinfo)
raw     <-  mdf[7:(ncol(mdf))]
rowinfo <- mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
Wavecut0.3<-plot_pca(tmp1,tmp2,color_label = "batch")

#After WaveICA2.0 Cutoff of 0
mdf <- wave_0_mdf
mdf<-mdf %>% mutate(rowid = row_number()) %>% relocate(rowid, .before = sample)
rowinfo <- mdf %>% select(rowid, sample, age, batch, type, sample_id)

rm(rowinfo)
raw     <-  mdf[7:(ncol(mdf))]
rowinfo <- mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
Wavecut0<-plot_pca(tmp1,tmp2,color_label = "batch")

#Plot

arrangement<- ggarrange(Wavecut1,Wavecut0.7,Wavecut0.5,Wavecut0.3,Wavecut0,
                    labels = c("1", "0.7", "0.5", "0.3","0"),font.label = list(size = 8, color = "black"),ncol = 3, nrow = 2,common.legend = TRUE, legend = "bottom")

annotate_figure(arrangement, top = text_grob("Testing the different Cutoffs", face = "italic", size = 15))
rm(arrangement)
```


## Taking the provided sample order (which removes some samples)

```{r}
rm(rowinfo,raw)
raw     <-  wave_withorder_mdf[7:(ncol(wave_withorder_mdf))]
rowinfo <- wave_withorder_mdf[0:6]

tmp1 <- rowinfo %>% filter(type %in% c("sample")) %>% mutate(rowid2 = row_number())
tmp2 <- raw[tmp1$rowid,]
plot_pca(tmp1,tmp2,color_label = "age")
```

# Models

## 1
```{r}
training_DF <- wave_withorder_mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

wave_1 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[1,] = data.frame(getTrainPerf(wave_1), Name = paste0("waveICA2.0_Cutoff_1"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")
```

## 0.7
```{r}
training_DF <- wave_0.7_mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

wave_0.7 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[2,] = data.frame(getTrainPerf(wave_0.7), Name = paste0("waveICA2.0_Cutoff_0.7"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")
```

## 0.5
```{r}
training_DF <- wave_0.5_mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

wave_0.5 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[3,] = data.frame(getTrainPerf(wave_0.5), Name = paste0("waveICA2.0_Cutoff_0.5"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")
```

## 0.3
```{r}
training_DF <- wave_0.3_mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

wave_0.3 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[4,] = data.frame(getTrainPerf(wave_0.3), Name = paste0("waveICA2.0_Cutoff_0.3"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")
```

## 0
```{r}
training_DF <- wave_0_mdf %>% filter(type=="sample") %>%  select(-sample,-batch,-type,-sample_id, -rowid)
training_DF[is.na(training_DF)] <- 0

training_x <- training_DF %>% select(-age) %>% as.data.frame()
training_y <- training_DF$age

trControl <- trainControl(method = "repeatedcv", number = 10, repeats= 25, verboseIter = F, savePredictions = "final")

wave_0 <- train(x = training_x, 
               y = training_y, 
          method = "glmnet",
          tuneLength = 5,
       trControl = trControl,
       metric = 'RMSE'
      )

results[5,] = data.frame(getTrainPerf(wave_0), Name = paste0("waveICA2.0_Cutoff_0"), QC = "4th_root + PCA outlier removal + Bad features removal + WaveICA2.0")

results
```


# Plot showing RMSEs


## 1
```{r}
error<-wave_1$pred %>%
  filter(alpha == wave_1$bestTune$alpha & lambda == wave_1$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "1")
```

## 0.7
```{r}
error1<-wave_0.7$pred %>%
  filter(alpha == wave_0.7$bestTune$alpha & lambda == wave_0.7$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "0.7")

error<-rbind(error,error1)
```

## 0.5
```{r}
error1<-wave_0.5$pred %>%
  filter(alpha == wave_0.5$bestTune$alpha & lambda == wave_0.5$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "0.5")

error<-rbind(error,error1)
```

## 0.3
```{r}
error1<-wave_0.3$pred %>%
  filter(alpha == wave_0.3$bestTune$alpha & lambda == wave_0.3$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "0.3")

error<-rbind(error,error1)
```

## 0 
```{r}
error1<-wave_0$pred %>%
  filter(alpha == wave_0$bestTune$alpha & lambda == wave_0$bestTune$lambda) %>% #subset 
  separate(Resample, c("fold", "rep"), "\\.") %>% 
  group_by(rep) %>% #group by replicate
  summarise(rmse = RMSE(obs, pred)) %>% 
  as.data.frame() %>% 
  mutate(model = "0")

error<-rbind(error,error1)
```

## Plotting
```{r fig.asp = 0.6, fig.width = 10}
error %>% ggplot(aes(x=model,y=rmse, color=model)) + 
  geom_boxplot(outlier.colour = "red") + 
  geom_boxplot(outlier.colour="red", outlier.shape=1, outlier.size=8) +  geom_jitter(shape=16, position=position_jitter(0)) +
  scale_color_brewer(palette="Set2") +
  ggtitle("RMSE of WaveICA2.0 with different Cutoff parameters") + 
  theme(plot.title = element_text(face="italic"))
```

# Saving the models

```{r}

rm(mdf,ms,merged,raw,rowinfo,training_DF,training_x,trControl,training_y,plot_pca,results,sampleorder,test,test2,tmp1,tmp2,tmp3,tmp4,wave_original_mdf,wave_withorder_mdf,order,WD)
#save.image(file = "models_waveICA2.0.RData")
```
